version: '3.0'

services:
  client:
    container_name: client
    build:
      context: ./src/client/
      dockerfile: Dockerfile
    volumes:
      - ./src/client:/app
      - /app/node_modules
    ports:
      - '3001:3000'
  server:
    container_name: backend
    build:
      context: ./src/backend/
      dockerfile: Dockerfile
    volumes:
      - '/tmp'
    ports:
      - '8080:8080'
