version: '3.0'

services:
#   client:
#     container_name: client
#     build:
#       context: ./client/
#       dockerfile: Dockerfile
#     ports:
#         - '3000:80'
  server:
    container_name: backend
    build:
      context: ./src/backend/
      dockerfile: Dockerfile
    volumes:
      - '/tmp'
    ports:
      - '8080:8080'